# Site
name: "Ruff thoughts"
description: "Phil Ruff's Blog"
meta_description: "Professional thoughts of a agile, lean devops practioner."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-24684003-5'
# disqus: 'demowebsite'
mailchimp-list: 'http://eepurl.com/gpjhPv'

# Authors
authors:
  phil:
    name: Phil
    display_name: Phil
    gravatar: a444709b3f00ec237742fad3ffd6c525
    email: phil.ruff+blog@gmail.com
    web: https://paruff.github.io/
    twitter: https://twitter.com/paruff
    description: "A lean agilist focused on devops and cloud with a paasion for life long learning."
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-avatar
  - github-pages-health-check
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
